parameters:
#    app_battery.example.class: App\BatteryBundle\Example

services:
#    app_battery.example:
#        class: %app_battery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
